<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RollForward>Major</RollForward>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ini-parser-netstandard" Version="2.5.2" />
		<PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
		<PackageReference Include="SharpCompress" Version="0.39.0" />
		<PackageReference Include="YiQiDong.Core" Version="2.4.10" />
	</ItemGroup>

	<ItemGroup>
		<None Update="config.ini">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="YiQiDong.Image.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
